#[doc = r" Register block"]
#[repr(C)]
pub struct RegisterBlock;
#[doc = "Description collection: Trigger n for triggering the corresponding TRIGGERED\\[n\\] event"]
pub struct TASKS_TRIGGER;
#[doc = "Description collection: Trigger n for triggering the corresponding TRIGGERED\\[n\\] event"]
pub mod tasks_trigger;
#[doc = "Description collection: Event number n generated by triggering the corresponding TRIGGER\\[n\\] task"]
pub struct EVENTS_TRIGGERED;
#[doc = "Description collection: Event number n generated by triggering the corresponding TRIGGER\\[n\\] task"]
pub mod events_triggered;
#[doc = "Enable or disable interrupt"]
pub struct INTEN;
#[doc = "Enable or disable interrupt"]
pub mod inten;
#[doc = "Enable interrupt"]
pub struct INTENSET;
#[doc = "Enable interrupt"]
pub mod intenset;
#[doc = "Disable interrupt"]
pub struct INTENCLR;
#[doc = "Disable interrupt"]
pub mod intenclr;
