#[repr(C)]
pub struct PSEL;
pub mod psel;
#[repr(C)] pub struct TXD;
pub mod txd;
pub struct TASKS_SUSPEND;
pub mod tasks_suspend;
pub struct EVENTS_ERROR;
pub mod events_error;
pub struct EVENTS_RXSTARTED;
pub mod events_rxstarted;
pub struct EVENTS_LASTRX;
pub mod events_lastrx;
pub struct SHORTS;
pub mod shorts;
pub struct INTENSET;
pub mod intenset;
pub struct ERRORSRC;
pub mod errorsrc;
pub struct FREQUENCY;
pub mod frequency;
