language: rust
rust: stable
env:
  global:
    - TARGET_BUILD=thumbv7em-none-eabi
    - RUSTFLAGS="--deny warnings"

install:
  - rustup target add $TARGET_BUILD
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo check --target $TARGET_BUILD

notifications:
  email:
    on_success: never
